### ISSUE TITLE
Playbook file as executable?

### ISSUE THREAD

**Issue by wilsonmar** [Condla/ansible-playground#2]
https://github.com/Condla/ansible-playground/blob/master/raspbian-bootstrap/README.md
contains:
```
# Execute playbook
./playbook.yml
```
But are .yml files executable?
I thought the way to use them is
```
ansible-playbook playbook.yml -i hosts
```

**Comment by Condla** [comment]
Every file can be made executable with the correct shebang.

If you have a look at the top of the playbook.yml you can see:

```
#!/usr/bin/env ansible-playbook
```

Since the file is made executable the two lines you posted in your comment are equivalent.

Makes sense?
